# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = “/extras/https://crwn-clothing.com/”
  to = “https://crwn-clothing.com/"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"