[[redirects]]
  from = "/extras/"
  to = "https://crwn-clothing.com/"
  status = 200
  force = true
  headers = {
    X-From = "Netlify"
    Origin: "https://gleeful-mandazi-e6b5a7.netlify.app/extras",
    Access-Control-Request-Method: GET, OPTIONS
    }
